import React from 'react';
import { CleaningServicesRounded, LocalDrinkRounded, RiceBowlRounded, WaterDropRounded } from '@mui/icons-material';

export const TURN_TYPES = {
    water: {
        type: 'water',
        label: 'Water',
        title: 'Water Turn',
        noun: 'water',
        verb: 'brought water',
        action: 'I Brought Water',
        coverAction: 'I Brought Water For This Turn',
        obligation: 'bring water',
        due: 'Water due',
        mark: 'Mark Water Brought',
        markDesc: 'Record that a partner brought water. This fulfills that partner\'s obligation for the cycle. Use it only when they genuinely brought the water.',
        historyTitle: 'Water Turn History',
        icon: WaterDropRounded,
        cardIcon: <WaterDropRounded />,
        actionIcon: <LocalDrinkRounded />,
    },
    cleaning: {
        type: 'cleaning',
        label: 'Cleaning',
        title: 'Flat Cleaning Turn',
        noun: 'flat cleaning',
        verb: 'cleaned the flat',
        action: 'I Cleaned the Flat',
        coverAction: 'I Cleaned For This Turn',
        obligation: 'clean the flat',
        due: 'Cleaning due',
        mark: 'Mark Cleaning Done',
        markDesc: 'Record that a partner cleaned the flat. This fulfills that partner\'s obligation for the cycle. Use it only when they genuinely cleaned.',
        historyTitle: 'Flat Cleaning History',
        icon: CleaningServicesRounded,
        cardIcon: <CleaningServicesRounded />,
        actionIcon: <CleaningServicesRounded />,
    },
    rice: {
        type: 'rice',
        label: 'Rice',
        title: 'Rice Turn',
        noun: 'rice',
        verb: 'brought rice',
        action: 'I Brought Rice',
        coverAction: 'I Brought Rice For This Turn',
        obligation: 'bring rice',
        due: 'Rice due',
        mark: 'Mark Rice Brought',
        markDesc: 'Record that a partner brought rice. This fulfills that partner\'s obligation for the cycle. Use it only when they genuinely brought the rice.',
        historyTitle: 'Rice Turn History',
        icon: RiceBowlRounded,
        cardIcon: <RiceBowlRounded />,
        actionIcon: <RiceBowlRounded />,
    },
};

export const getTurnTypeConfig = (type) => TURN_TYPES[type] || TURN_TYPES.water;